pipeline {
	agent any
	tools {
		// Set names in Global Tools:
		gradle 'Gradle5.1'
	}
	stages {
		stage('Compile and Build  Stage') {
			steps {
				sh './gradlew assembleDebug'
			}
		}

		stage('Adding variables to path') {
			steps {
				sh 'CLASSPATH=/Library/Java/Extensions/applicationcenterdeploytool.jar:/Library/Java/Extensions/json4j.jar'
			}
		}

		stage('uploading into IBM app store') {
			steps {
				sh 'java com.ibm.appcenter.Upload -s https://www.rfmp-mfp-dev.com:443 -c applicationcenter -u admin -p APPCTNR@dmin#Dev19 -y -f app/build/outputs/apk/debug/app-debug.apk'
			}
		}

		stage('Testing Stage') {
			steps {
				sh 'ls'
			}
		}

	}

	post {
		always {
			archiveArtifacts artifacts: '**/build/outputs/apk/debug/*.apk', fingerprint: true
//			junit 'build/reports/**/*.xml'
		}
	}
}
