package suncor.com.android.utilities

object Constants {

    const val STATUS = "status"
    const val ACCEPT_LANGUAGE = "Accept-Language"
    const val ERROR_CODE = "errorCode"
    const val USER_ID = "user_id"
    const val USER_ID_1 = "userID"
    const val TRUE = "true"
    const val FALSE = "false"
    const val IS_RBC_LINKED = "is_linked_rbc"
    const val BUILD_NUMBER = "BuildNumber"
    const val ERROR_MESSAGE = "errorMessage"
    const val ALERT_TITLE = "alertTitle"
    const val ALERT = "alert"
    const val ACTION_MENU = "ActionMenu"
    const val FORM_NAME = "formName"
    const val FORM_START = "form_start"
    const val STEP_NAME = "stepName"
    const val FORM_STEP = "form_step"
    const val SPLASH = "Splash"
    const val ERROR_LOG = "error_log"
    const val ALERT_SELECTION = "alertSelection"
    const val FORM_SELECTION = "formSelection"
    const val ALERT_INTERACTION = "alert_interaction"
    const val ACTIVATE_PETRO_POINTS_CARD = "Activate Petro-Points Card"
    const val ACTIVATE_PETRO_POINTS_SIGN_UP = "Petro Points Sign Up Activate"
    const val ACTIVE_SESSION = "Active Session"
    const val ACTIVATE_SUCCESS = "activate-success"
    const val SIGNUP_SUCCESS = "sign-up-success"
    const val PERSONAL_INFORMATION = "Personal Information"
    const val ADDRESS = "Address"
    const val PARAMETERS = "parameters"
    const val SCROLL = "scroll"
    const val SCROLL_DEPTH_THRESHOLD = "scrollDepthThreshold"
    const val LOGIN_FORCE_NEW_PASSWORD = "Login Force New Password"
    const val LOGIN = "Login"
    const val HOME = "Home"
    const val AUTHORIZED = "Authorized"
    const val NEW = "New"
    const val PUMP_PRE_AUTHORIZED = "Pump PreAuthorized"
    const val CARWASH_TICKET = "Carwash Ticket"
    const val ALPHA = "alpha"
    const val TRANS_Y = "translationY"
    const val PAY_AT_PUMP = "Pay at Pump"
    const val SOMETHING_WRONG = "Something went wrong on our side"
    const val FUELING_COMPLETE = "Fuelling Complete"
    const val PAY_AT_PAUMP_AUTH_LOADING = "pay-at-pump-fuelling-authorizing-loading"
    const val PAY_AT_PAUMP_PRE_AUTH_LOADING = "pay-at-pump-preauthorize-loading"
    const val PAY_AT_PAUMP_PRE_AUTH = "pay-at-pump-preauthorize"
    const val PAY_AT_PAUMP_AUTH = "pay-at-pump-fuelling-authorizing"
    const val PAY_AT_PAUMP_FUELING_BEGIN = "pay-at-pump-fuelling-will-begin"
    const val PAY_AT_PAUMP_FUELING_BEGUN = "pay-at-pump-fuelling-has-begun"
    const val PAY_AT_PAUMP_FUELING_CANCELED = "pay-at-pump-fuelling-transaction-cancelled"
    const val PAY_AT_PAUMP_FUELING_ALMOST_COMPLETE = "pay-at-pump-fuelling-almost-complete"
    const val PAY_AT_PAUMP_FUELING_COMPLETE = "Fuelling Complete"
    const val TEMP_PAYMENT = "tempPayment"
    const val SELECTED_PAYMENT = "selectedPayment"
    const val DIALOG_TITLE = "dailog"
    const val CANCELLED = "Cancelled"
    const val CANCELED = "CANCELED"
    const val GOOGLE = "google"
    const val CREDIT_CARD_1 = "credit_card"
    const val READY_PAY_FAILURE = "isReadyToPay failed"
    const val CREDIT_CARD = "Credit Card"
    const val GPAY = "Google Pay"
    const val GPAY_CANCEL_USER = "Google pay transaction cancel by user"
    const val GPAY_ERROR_MSG = "Google Pay error , message"
    const val BIOMETRICS_FAILURE = "Biometrics fails"
    const val TRANSACTION_FAILURE_ERROR_CODE = "Transaction fails, errorCode : "
    const val PUMP_REG_FAILS_ERROR_CODE = "Pump Registration fails, errorCode : "
    const val SOEMTHING_WRONG_ERROR_CODE = "Something went wrong on our side, errorCode : "
    const val AVAILABLE = "Available"


    const val VIEW_ITEM = "view_item"
    const val SELECT_CONTENT = "select_content"
    const val VIDEO_START = "video_start"
    const val VIDEO_THRESHOLD_25 = "video_threshold_25"
    const val VIDEO_THRESHOLD_50 = "video_threshold_50"
    const val VIDEO_THRESHOLD_75 = "video_threshold_75"
    const val VIDEO_COMPLETE = "video_complete"
    const val FORM_COMPLETE ="form_complete"
    const val FORM_ERROR ="form_error"
    const val NAVIGATION = "navigation"
    const val BUTTON_TAP = "button_tap"
    const val PAYMENT_PREAUTHORIZE = "payment_preauthorize"
    const val PAYMENT_COMPLETE = "payment_complete"
    const val INTERSITE = "intersite"
    const val INFO_TAP = "info_tap"
    const val MENU_TAP = "menu_tap"

    const val ITEM_ID = "item_id"
    const val ITEM_NAME = "item_name"
    const val CREATIVE_NAME = "creative_name"
    const val CREATIVE_SLOT = "creative_slot"
    const val CONTENT_TYPE = "content_type"
    const val PROMOTIONS = "promotions"
    const val VIDEO_TITLE = "videoTitle"
    const val ACTIONBAR_TAP = "actionBarTap"
    const val BUTTON_TEXT = "buttonText"
    const val CARD_TYPE = "cardType"
    const val DETAIL_ERROR_MESSAGE = "detailErrorMessage"
    const val PAYMENT_METHOD = "paymentMethod"
    const val FUEL_AMOUNT_SELECTION = "fuelAmountSelection"
    const val INTERSITE_URL = "intersiteURL"
    const val INFO_TEXT = "infoText"
    const val MENU_SELECTION = "menuSelection"

    const val INTERNAL_PROMOTIONS = "Internal Promotions"
    const val ACTIVATE_WNG = "Activate Wash by Wash & Go card"
    const val ACTIVATE_SP = "Activate Wash by Season Pass card"
    const val NONE = "None"
    const val DEFAULT_ERROR_SUNCORXXXX = "SUNCORXXXX"

    //Paths
    const val GET_LOCATIONS_ADAPTER__PATH = "/adapters/suncor/v3/rfmp-secure/locations"

    //Signup methods
    const val JOIN_NO_CARD="Join-No-Card"
    const val JOIN_YES_CARD="Join-Yes_card"
}