package suncor.com.android.utilities

object Constants {

    const val STATUS = "status"
    const val ACCEPT_LANGUAGE = "Accept-Language"
    const val ERROR_CODE = "errorCode"
    const val ERROR_MESSAGE = "errorMessage"
    const val ALERT_TITLE = "alertTitle"
    const val ALERT = "alert"
    const val ACTION_MENU = "ActionMenu"
    const val FORM_NAME = "formName"
    const val FORM_START = "form_start"
    const val FORM_STEP = "form_step"
    const val SPLASH = "Splash"
    const val ERROR_LOG = "error_log"
    const val ALERT_SELECTION = "alertSelection"
    const val ALERT_INTERACTION = "alert_interaction"
    const val ACTIVATE_PETRO_POINTS_CARD = "Activate Petro-Points Card"
    const val ACTIVATE_PETRO_POINTS_SIGN_UP = "Petro Points Sign Up Activate"
    const val ACTIVE_SESSION = "Active Session"
    const val ACTIVATE_SUCCESS = "activate-success"
    const val SIGNUP_SUCCESS = "sign-up-success"
    const val PERSONAL_INFORMATION = "Personal Information"
    const val ADDRESS = "Address"
    const val PARAMETERS = "parameters"
    const val SCROLL = "scroll"
    const val SCROLL_DEPTH_THRESHOLD = "scrollDepthThreshold"
    const val LOGIN_FORCE_NEW_PASSWORD = "Login Force New Password"
    const val LOGIN = "Login"
    const val HOME = "Home"
    const val AUTHORIZED = "Authorized"
    const val NEW = "New"
    const val PUMP_PRE_AUTHORIZED = "Pump PreAuthorized"
    const val CARWASH_TICKET = "Carwash Ticket"
    const val ALPHA = "alpha"
    const val TRANS_Y = "translationY"
    const val PAY_AT_PUMP = "Pay at Pump"
    const val SOMETHING_WRONG = "Something went wrong on our side"
    const val FUELING_COMPLETE = "Fuelling Complete"
    const val PAY_AT_PAUMP_AUTH_LOADING = "pay-at-pump-fuelling-authorizing-loading"
    const val PAY_AT_PAUMP_AUTH = "pay-at-pump-fuelling-authorizing"
    const val PAY_AT_PAUMP_FUELING_BEGIN = "pay-at-pump-fuelling-will-begin"
    const val PAY_AT_PAUMP_FUELING_BEGUN = "pay-at-pump-fuelling-has-begun"
    const val PAY_AT_PAUMP_FUELING_CANCELED = "pay-at-pump-fuelling-transaction-cancelled"
    const val PAY_AT_PAUMP_FUELING_ALMOST_COMPLETE = "pay-at-pump-fuelling-almost-complete"
    const val PAY_AT_PAUMP_FUELING_COMPLETE = "Fuelling Complete"
    const val CANCELLED = "Cancelled"
    const val CANCELED = "CANCELED"
    const val GOOGLE = "google"

    //Paths
    const val GET_LOCATIONS_ADAPTER__PATH = "/adapters/suncor/v3/rfmp-secure/locations"
}