package suncor.com.android.googlepay.passes


data class LoyalityData(
        var barcode: String? = null,
        var barcodeDisplay: String? = null,
        var localizedLanguage: String? = "fr",
        var defaultLanguage: String? = "en-GB",
        var barcodeType: String? = "pdf417",
        var nameLabel: String? = null,
        var nameLocalizedLabel: String? = null,
        var nameValue: String? = null,
        var emailLabel: String? = null,
        var emailLocalizedLabel: String? = null,
        var emailValue: String? = null,
        var detailsLabel: String? = null,
        var detailsLocalizedLabel: String? = null,
        var detailsValue: String? = null,
        var detailsLocalizedValue: String? = null,
        var valuesLabel: String? = null,
        var valuesLocalizedLabel: String? = null,
        var valuesValue: String? = null,
        var valuesLocalizedValue: String? = null,
        var howToUseLabel: String? = null,
        var howToUseLocalizedLabel: String? = null,
        var howToUseValue: String? = null,
        var howToUseLocalizedValue: String? = null,
        var termConditionLabel: String? = null,
        var termConditionLocalizedLabel: String? = null,
        var termConditionValue: String? = null,
        var termConditionLocalizedValue: String? = null,
        var currentLat: String? = null,
        var currentLng: String? = null,

)
