name: Android CI

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
      
    - name: Get time
      run: |
          echo FULL_DATE=$(TZ="Canada/Eastern" date) >> $GITHUB_ENV
    - name: Get date
      run: |
          echo SHORT_DATE=$(TZ="Canada/Eastern" date +%Y%m%d%H) >> $GITHUB_ENV
          
    # this gets the first 6 characters of the git hash, used for labelling
    - name: Get short hash
      run: |
          short=${GITHUB_SHA::6}
          echo SHORT_HASH=$short >> $GITHUB_ENV
          
    
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and Build
      run: ./gradlew clean
    - name: Compile and Build
      run: ./gradlew assemble${env.BUILD_ENV}${env.FEATURE}Release
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Update app buildSettings.properties to show build date
      run: |
          sed -i '' -e 's/__BUILD_DATE__/${{ env.FULL_DATE }}/g' "app/src/main/assets/buildSettings.properties"
          sed -i '' -e 's/__BUILD_SHA__/${{ env.SHORT_HASH }}/g' "app/src/main/assets/buildSettings.properties"
    
    
