name: Test Coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      # this on failure, the workflow does not fail even if this upload fails but throws the error on email
      - name: Announce if build fails with info
        uses: actions/failure-info@v2
        if_error_or_failure:
          if: >-
            github.event.state == 'error' ||
            github.event.state == 'failure'
          steps:
            - env:
                DESCRIPTION: ${{ github.event.description }}
              run: |
                echo The status is error or failed: $DESCRIPTION
                echo gh run view --job job-id --log-failed | grep error

      - name: Add coverage to PR
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}